apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-scaler
  namespace: myscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-scaler
  template:
    metadata:
      labels:
        app: calendar-scaler
    spec:
      containers:
      - name: scaler
        image: calendar-scaler:latest
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgresql-password
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: myscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgresql-password
        - name: PGOPTIONS
          value: "--log_statement=all --log_min_duration_statement=0"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: calendar-scaler
  namespace: myscaler
spec:
  ports:
  - port: 6000
    targetPort: 6000
  selector:
    app: calendar-scaler
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: myscaler
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale-target
  namespace: myscaler
spec:
  replicas: 0
  selector:
    matchLabels:
      app: scale-target
  template:
    metadata:
      labels:
        app: scale-target
    spec:
      containers:
      - name: http
        image: nginx:latest
        imagePullPolicy: IfNotPresent